apiVersion: v1
kind: Service
metadata:
  labels:
    component: etcd
    tier: control-plane
  name: etcd-svc
  namespace: kube-system
spec:
  externalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 32379
    port: 2379
    protocol: TCP
    targetPort: 2379
  selector:
    component: etcd
    tier: control-plane
  sessionAffinity: None
  type: NodePort